# Generated by Django 4.1.3 on 2023-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H_m',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_h_m',
            },
        ),
        migrations.CreateModel(
            name='intake_data',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Bridge', models.FloatField(null=True)),
                ('Upstream', models.FloatField(null=True)),
                ('Downstream', models.FloatField(null=True)),
                ('Bridge_Shaped', models.FloatField(null=True)),
                ('Upstream_Shaped', models.FloatField(null=True)),
                ('Downstream_Shaped', models.FloatField(null=True)),
                ('Bridge_Code', models.BigIntegerField(null=True)),
                ('Upstream_Code', models.BigIntegerField(null=True)),
                ('Downstream_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'box_intake_data',
            },
        ),
        migrations.CreateModel(
            name='P_kW',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_p_kw',
            },
        ),
        migrations.CreateModel(
            name='U1_P_kW',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_u1_p_kw',
            },
        ),
        migrations.CreateModel(
            name='U1_Y',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_u1_y',
            },
        ),
        migrations.CreateModel(
            name='U2_P_kW',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_u2_p_kw',
            },
        ),
        migrations.CreateModel(
            name='U2_Y',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_u2_y',
            },
        ),
        migrations.CreateModel(
            name='Uab_kV',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_uab_kv',
            },
        ),
        migrations.CreateModel(
            name='Ubc_kV',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_ubc_kv',
            },
        ),
        migrations.CreateModel(
            name='Uca_kV',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(null=True)),
                ('Minimum', models.FloatField(null=True)),
                ('Maximum', models.FloatField(null=True)),
                ('Average', models.FloatField(null=True)),
                ('Minimum_Shaped', models.FloatField(null=True)),
                ('Maximum_Shaped', models.FloatField(null=True)),
                ('Average_Shaped', models.FloatField(null=True)),
                ('Minimum_Code', models.BigIntegerField(null=True)),
                ('Maximum_Code', models.BigIntegerField(null=True)),
                ('Average_Code', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'scada_uca_kv',
            },
        ),
    ]
